// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7J-iOF7KclrtczGWVzGfyHXghuJvUew',
    appId: '1:839982160411:android:fbe5214f6d32259b0136be',
    messagingSenderId: '839982160411',
    projectId: 'chat-4u-5c7dc',
    storageBucket: 'chat-4u-5c7dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZK635aRv8O6s74J_rNPgFRigy8TMKiMA',
    appId: '1:839982160411:ios:45679a68cf1c0c2e0136be',
    messagingSenderId: '839982160411',
    projectId: 'chat-4u-5c7dc',
    storageBucket: 'chat-4u-5c7dc.appspot.com',
    androidClientId: '839982160411-nbe34fq74922n02g2ta53dq80haheoe8.apps.googleusercontent.com',
    iosClientId: '839982160411-kpiqt6q3rr2pq9cm296c48s2cq3ho78n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat4u',
  );

}